[[redirects]]
  from = "/api/*"
  to = "https://api-twypgdks3a-uc.a.run.app/:splat"
  status = 200
  force = true

# Your normal SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
